### PR TITLE
Add fumaroles and lava sinkholes

### PR DESCRIPTION
**Pull request by Treer**
Also adds netherrack stairs, as they are used in fumaroles 

[fumaroles and sinkholes can be seen in this video](https://www.youtube.com/watch?v=QegvRIszeI8) - skip to 2:30

Fumaroles are added to both the old (noBiomes) mapgen and the biomes mapgen, but lava sinkholes have been excluded from the old mapgen because the old mapgen removes lava from overdraw areas, so decorations involving lava will often have the lava missing depending on whether neighbour chunks were already emerged or not before the decoration was placed.

Both fumaroles and sinkholes add some danger to the Nether (#4), though the fumaroles are more about adding atmosphere and flavour.

If fumarole nodes are taken to the surface, they continue to smoke, but don't ignite or throw up the particle effects, making the nodes pillagable for the cottage chimney industry etc.

You can't see any lava sinkholes in this image, but they look like 2×2 squares of nethersand on the floor.
nether fumaroles copy

~~Fumarole smoke looks good in its own right but I'm not sure it's a match in artistic flavour, perhaps masses of square particles would be better, or pixelated square smoke puffs?~~ Smoke puffs have been changed from round to square

nether chimney chimney screenshot_20200208_132302

~~Ideally there would be lava under the fumaroles - it adds great unease when you walk over one and can see lava deep down below, but currently it's sand because lava is a lightsource and engine limitations mean mesh or nodebox nodes have to have paramtype of "light" and so light up when they have lava under them. Also the old mapgen doesn't handle lava well. I'm tempted to solve this one either with an airlike node which doesn't transmit light (paramtype="none") or an alt lava node which has paramtype="none" - both being hacks, as I'm unsure of any non-hacky way to display a node texture at full brightness without transmitting light (entities can do this with a negative glow value)~~ Solved with an airlike node which doesn't transmit light ("nether:airlike_darkness")

I don't think the fumarole sound feels particularly connected to the fumaroles when playing the game, but it's adding something aural and spooky to the nether so I've left it in.

### CODE REVIEW

**Comment by Bastrabun** [comment]
Any chance this is going to be merged sometime?

Asking, because it's open since January :)

**Comment by Treer** [comment]
I wouldn't mind some feedback on it - from players as much as modders.

**Comment by dacmot** [comment]
Disclaimer: I'm running on your nether-core branch which is several commits ahead of this one.

* the airlike_darkness hack
  * Not completely sure what this should do. When I look down fumeroles, I see lava. But they don't seem to emit light. Is that what it is?
* sinkholes
  * Great, except they don't collapse unless you actively touch them with your hand or a tool (sand falling). So you figure out pretty quick not to touch them.
* it adds netherrack stairs (#3)
   * Fine
* it adds stairs to make off-axis holes with 4 sideways rotated stairs. (hmm, this should be tested with moreores, as moreores replaces stairs with its own ones)
   * Fine, though I did not test with moreores.
* the fumerole sound. It doesn't sound like something connected to fumeroles, but does seem to add eerie ambiance.
    * is it the wind whistling sound? I do like the ambiance it breaks.
* the smoke puff texture / style
    * Much prefer the squarish texture than the round one. It looks fantastic. I'm using it to make chimneys for my houses top-side!
* my inability to prevent fumeroles sometimes appearing under fumeroles (it doesn't really matter, but looks messy in noclip/xray mode).
    * Doesn't matter in my opinion. The fumeroles clusters are great.
* timings - fumeroles have a timer each, and can catch fire, extinguish, smoke, or have a particle effect splash.  messes with the stairs)
    * Looks great too. Seems random enough to not notice any pattern.
* fumerole clump perlin size & distribution, lone fumerole spacing.
    * Seems fine to me.

Overall: I'm loving the nether! With all these changes and the few extras from nether-core, though I did not experience the mod without these changes. I love the look, the glowstones, fumeroles, and sand sinkholes. With the giant lava waterfalls and spills, it's simply awe-some. I can't wait for this to be merged, and more!

**Comment by Treer** [comment]
Thanks for that point by point feedback, sounds like I may be over-worrying.

> the airlike_darkness hack
>>   Not completely sure what this should do. When I look down fumaroles, I see lava. But they don't seem to emit light. Is that what it is? If so, then yes, it make it all the more surprising and scary.

Yeah, the purpose was to have fumaroles blend into the netherrack instead of looking like lights, it's a node that's like air but which light doesn't pass through. Placing airlike_darkness above fumarole lava prevents the area lighting up.

I grabbed some screenshots to demonstrate the difference and I think there's been some engine improvements to lighting or how light gets transmitted through mesh and nodebox nodes - the whole node doesn't light up any more, but the airlike_darkness hack is still needed to prevent the area around the fumarole from being lit.

airlikedarkness1

airlikedarkness2

> it make it all the more surprising and scary

Good point, it's a side-effect of trying to have the fumaroles blend, but you're right - those glimpses of lava _are_ more unexpected / surprising / scary when running in the dark, or without a lighting cue.

> the fumerole sound. It doesn't sound like something connected to fumeroles, but does seem to add eerie ambiance.
>> is it the wind whistling sound? I do like the ambiance it brings.

Yeah, it happens each time a fumarole starts.

**Comment by Bastrabun** [comment]
*the airlike_darkness hack

Nice trick. It makes the whole place a bit darker than without, and that's a good thing IMO. The nether isn't meant to be lit like an XMAS tree.

*sinkholes

They're easy to spot, since they're always 2x2. Is there a way to make them a little bit more ... random? Like 2x2, 2x3, 4x2, 2x1+2x3?
    
*it adds netherrack stairs (#3)
*it adds stairs to make off-axis holes with 4 sideways rotated stairs. (hmm, this should be tested with moreores, as moreores replaces stairs with its own ones)

I guess you mean moreblocks (not moreores). When moreblocks is enabled, netherrack cannot be cut in the saw and it keeps its default-like crafting recipe. Moreblocks introduces a second, mirrored one.

Maybe detect the existence of moreblocks and then register stairs with them if it exists and use those? That's how most of the other mods do it if they wish to introduce stairs.   
    
*the fumerole sound. It doesn't sound like something connected to fumeroles, but does seem to add eerie ambiance.

It does and I like it.

*the smoke puff texture / style

Fits well, I bet palyers will love using those as chimney tops.

my inability to prevent fumeroles sometimes appearing under fumeroles (it doesn't really matter, but looks messy in noclip/xray mode).

I doubt anyone cares or even goes "Nah, can't use that thing. That's not realistic, because the nether has to work this and that way!"

*timings - fumeroles have a timer each, and can catch fire, extinguish, smoke, or have a particle effect splash.
messes with the stairs)

Not too rare, not too often, at least in my tests. The effect wears out when there's always going something on, it's more a surprise when a new event happens after the player nearly forgot the last one.

*fumerole clump perlin size & distribution, lone fumerole spacing.

Not too rare, not too often, at least in my tests.

Looks like I agree with most @dacmot said. Also: Seems like you are the only dev that currently cares about the nether. Don't hesitate to make creative choices to make your vision of the nether come true :)

**Comment by Treer** [comment]
Finished some compatibility testing with moreblocks - I don't mind if netherbrick is fully registered with moreblocks but not netherrack, and we can change that if the goal of moreblocks is to register all the blocks.
The feedback was positive, so merged, and thanks @dacmot and @Bastrabun for taking a look at this and providing feedback.

**Pull request merged**
