### PR TITLE
Add nether based tools to mod

### PR DESCRIPTION
**Pull request by lortas**
Just a first try, to have tools build out of nether. There is space for improvement. :-)

### CODE REVIEW

**Comment by SmallJoker** [comment]
Looks good. @Treer - opinions?

**Comment by Treer** [comment]
I like to make newly introduced game elements optional in the settings, in hope of aiding anyone trying to build games or custom servers, so I'd suggest a Nether Tools setting that defaults to true. That's not a demand though, as it's unclear to me how helpful that really is, and could be added later. If a setting were added then nether_compressed could go in the nodes file and not be affected.

Also update the attributions in the readme to cover the new assets.

I'm no judge of tool balance - happy for whatever lortas wants.

(hoping to get some time over Christmas to catch up with that other PR)

**Comment by Treer** [comment]
I had a play with this, and "Nether Compressed" seemed like an odd description for a node, how about
* "Enriched Netherrack"
* "Compressed Netherrack"
* "Crushed Netherbrick"
etc.

(again, just a comment, not a demand)

**Comment by lortas** [comment]
With "Nether Compressed" I tried to be conform with the following nodes from "moreblocks".
- Compressed Cobblestone
- Compressed Desert Cobblestone
- Compressed Dirt

But I also like the term "Enriched Netherrack". The intention of this node was to gather nether ore.
And combing nine Netherracks to "Enriched Netherrack", would enrich the containing nether.

**Comment by lortas** [comment]
By the way, the proposed textures are just images from "default" and "moreblocks" where I have changed the colors. If it is okay for everyone, just use the same owner/copyright/copyleft/... the origin had. I do not claim anything.

**Comment by Treer** [comment]
"Compressed Netherbrick" or "Compressed Netherrack" would be the way to go if you wanted to follow moreblocks node names like "Compressed Cobblestone".

"Nether Compressed" seemed odd to me because the word order was backwards and I think of "Nether" as a location or a mod, rather than a stone-type like Netherrack or Nether brick.

**Comment by lortas** [comment]
Ok, and while the new node is crafted out of Netherbrick, we should name it "Compressed Netherbrick".
This texture may better fits the new name: nether_brick_compressed

**Comment by Treer** [comment]
I can merge this now if you're ready

**Comment by lortas** [comment]
from my side, it is ready to merge.

**Pull request merged**
