### PR TITLE
Fix things to avoid warnings about deprecated method and definitions

### PR DESCRIPTION
**Pull request by sys4-fr**

### CODE REVIEW

**Comment by Treer** [comment]
Should the value written to `use_texture_alpha` check `minetest.features` for `use_texture_alpha_string_modes` ?

That question isn't only for sys4-fr - I'm never sure at what point to break free from supporting older versions.

**Comment by sys4-fr** [comment]
Yes I have seen recently some examples checking the `minetest.features` for `use_texture_alpha_string_modes` in other mods. I'm looking into that...

**Comment by sys4-fr** [comment]
Tested with Minetest 5.0.0 and 5.4.0.

**Review by SmallJoker — APPROVED** [review]
LGTM. WIll merge in a few days if there are no objections.

**Pull request merged**
